# Generated by Django 4.1.1 on 2022-09-24 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nikewebsite', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
