# Generated by Django 4.1.1 on 2022-09-24 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nikewebsite', '0004_post_slug_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
